# Her grammar konusu için önceden hazırlanmış 5 statik soru
# Bu sorular quiz açılınca anında gösterilir — OpenAI beklenmez
# Kullanıcı bu soruları çözerken arka planda batch 2 ve 3 üretilir

STATIC_GRAMMAR_QUESTIONS: dict[str, list] = {

    "articles": [
        {
            "id": "art-1", "type": "multiple_choice",
            "question": "She has ___ umbrella in her bag.",
            "options": ["a", "an", "the", "—"],
            "correct_answer": "an",
            "explanation": "Use 'an' before vowel sounds. 'Umbrella' starts with a vowel sound /ʌ/.",
            "difficulty": "easy",
        },
        {
            "id": "art-2", "type": "multiple_choice",
            "question": "I saw ___ dog in the park. ___ dog was very friendly.",
            "options": ["a / The", "the / A", "a / A", "the / The"],
            "correct_answer": "a / The",
            "explanation": "First mention uses 'a' (indefinite). Second mention uses 'the' (now specific).",
            "difficulty": "easy",
        },
        {
            "id": "art-3", "type": "multiple_choice",
            "question": "___ sun rises in the east.",
            "options": ["A", "An", "The", "—"],
            "correct_answer": "The",
            "explanation": "Use 'the' with unique things — there is only one sun.",
            "difficulty": "easy",
        },
        {
            "id": "art-4", "type": "multiple_choice",
            "question": "She is ___ engineer at a tech company.",
            "options": ["a", "an", "the", "—"],
            "correct_answer": "an",
            "explanation": "'Engineer' starts with a vowel sound /ɛ/, so 'an' is correct.",
            "difficulty": "medium",
        },
        {
            "id": "art-5", "type": "multiple_choice",
            "question": "___ dogs are loyal animals. (general statement)",
            "options": ["A", "An", "The", "—"],
            "correct_answer": "—",
            "explanation": "No article is used with plural nouns in general statements.",
            "difficulty": "medium",
        },
    ],

    "prepositions": [
        {
            "id": "prep-1", "type": "multiple_choice",
            "question": "The meeting is ___ Monday ___ 9 AM.",
            "options": ["on / at", "in / at", "at / on", "on / in"],
            "correct_answer": "on / at",
            "explanation": "Use 'on' for days of the week and 'at' for specific times.",
            "difficulty": "easy",
        },
        {
            "id": "prep-2", "type": "multiple_choice",
            "question": "She was born ___ 1995.",
            "options": ["at", "on", "in", "by"],
            "correct_answer": "in",
            "explanation": "Use 'in' for years, months, and longer periods of time.",
            "difficulty": "easy",
        },
        {
            "id": "prep-3", "type": "multiple_choice",
            "question": "The keys are ___ the table.",
            "options": ["in", "on", "at", "by"],
            "correct_answer": "on",
            "explanation": "Use 'on' for surfaces.",
            "difficulty": "easy",
        },
        {
            "id": "prep-4", "type": "multiple_choice",
            "question": "We travelled to Paris ___ train.",
            "options": ["with", "on", "by", "in"],
            "correct_answer": "by",
            "explanation": "Use 'by' to describe means of transport.",
            "difficulty": "medium",
        },
        {
            "id": "prep-5", "type": "multiple_choice",
            "question": "She has been working here ___ five years.",
            "options": ["since", "for", "during", "in"],
            "correct_answer": "for",
            "explanation": "Use 'for' with a duration of time. 'Since' is used with a point in time.",
            "difficulty": "medium",
        },
    ],

    "modal-verbs": [
        {
            "id": "mod-1", "type": "multiple_choice",
            "question": "You ___ smoke inside the building. It is forbidden.",
            "options": ["shouldn't", "mustn't", "couldn't", "mightn't"],
            "correct_answer": "mustn't",
            "explanation": "'Mustn't' expresses strong prohibition — it is not allowed.",
            "difficulty": "easy",
        },
        {
            "id": "mod-2", "type": "multiple_choice",
            "question": "I'm not sure, but she ___ be at the office today.",
            "options": ["must", "will", "might", "shall"],
            "correct_answer": "might",
            "explanation": "'Might' expresses possibility when you are not certain.",
            "difficulty": "easy",
        },
        {
            "id": "mod-3", "type": "multiple_choice",
            "question": "___ you speak any foreign languages when you were a child?",
            "options": ["Can", "Could", "Should", "Would"],
            "correct_answer": "Could",
            "explanation": "'Could' is used to talk about ability in the past.",
            "difficulty": "medium",
        },
        {
            "id": "mod-4", "type": "multiple_choice",
            "question": "You look tired. You ___ take a break.",
            "options": ["must", "can", "should", "would"],
            "correct_answer": "should",
            "explanation": "'Should' is used to give advice or recommendations.",
            "difficulty": "easy",
        },
        {
            "id": "mod-5", "type": "multiple_choice",
            "question": "___ I open the window? It's quite hot in here.",
            "options": ["Should", "Must", "Would", "Shall"],
            "correct_answer": "Shall",
            "explanation": "'Shall I...?' is used to offer to do something for someone.",
            "difficulty": "medium",
        },
    ],

    "conditionals": [
        {
            "id": "cond-1", "type": "multiple_choice",
            "question": "If you ___ water to 100°C, it boils.",
            "options": ["heat", "heated", "will heat", "would heat"],
            "correct_answer": "heat",
            "explanation": "Zero conditional uses Present Simple + Present Simple for general truths.",
            "difficulty": "easy",
        },
        {
            "id": "cond-2", "type": "multiple_choice",
            "question": "If it rains tomorrow, we ___ the match.",
            "options": ["cancel", "cancelled", "will cancel", "would cancel"],
            "correct_answer": "will cancel",
            "explanation": "First conditional (real future): If + Present Simple, will + base verb.",
            "difficulty": "easy",
        },
        {
            "id": "cond-3", "type": "multiple_choice",
            "question": "If I ___ a million dollars, I would travel the world.",
            "options": ["have", "had", "will have", "would have"],
            "correct_answer": "had",
            "explanation": "Second conditional (unreal present): If + Past Simple, would + base verb.",
            "difficulty": "medium",
        },
        {
            "id": "cond-4", "type": "multiple_choice",
            "question": "If she had studied harder, she ___ the exam.",
            "options": ["passes", "passed", "will pass", "would have passed"],
            "correct_answer": "would have passed",
            "explanation": "Third conditional (unreal past): If + Past Perfect, would have + past participle.",
            "difficulty": "hard",
        },
        {
            "id": "cond-5", "type": "multiple_choice",
            "question": "Which sentence is a correct first conditional?",
            "options": [
                "If I am rich, I would travel.",
                "If it rains, I will stay home.",
                "If she studied, she would pass.",
                "If he had known, he would come.",
            ],
            "correct_answer": "If it rains, I will stay home.",
            "explanation": "First conditional: If + Present Simple, will + base verb.",
            "difficulty": "medium",
        },
    ],

    "passive-voice": [
        {
            "id": "pass-1", "type": "multiple_choice",
            "question": "English ___ all over the world.",
            "options": ["speaks", "is spoken", "was spoken", "has spoken"],
            "correct_answer": "is spoken",
            "explanation": "Present Simple Passive: is/am/are + past participle.",
            "difficulty": "easy",
        },
        {
            "id": "pass-2", "type": "multiple_choice",
            "question": "The letter ___ yesterday.",
            "options": ["sent", "sends", "was sent", "is sent"],
            "correct_answer": "was sent",
            "explanation": "Past Simple Passive: was/were + past participle.",
            "difficulty": "easy",
        },
        {
            "id": "pass-3", "type": "multiple_choice",
            "question": "The new bridge ___ next year.",
            "options": ["builds", "is built", "will be built", "was built"],
            "correct_answer": "will be built",
            "explanation": "Future Passive: will be + past participle.",
            "difficulty": "medium",
        },
        {
            "id": "pass-4", "type": "multiple_choice",
            "question": "The report ___ by the manager at the moment.",
            "options": ["writes", "is writing", "is being written", "has been written"],
            "correct_answer": "is being written",
            "explanation": "Present Continuous Passive: is/am/are being + past participle.",
            "difficulty": "hard",
        },
        {
            "id": "pass-5", "type": "multiple_choice",
            "question": "Which sentence is in the passive voice?",
            "options": [
                "She wrote the novel in 2010.",
                "The novel was written in 2010.",
                "She has written many novels.",
                "She will write another novel.",
            ],
            "correct_answer": "The novel was written in 2010.",
            "explanation": "Passive voice: subject + be + past participle. The agent is optional.",
            "difficulty": "easy",
        },
    ],

    "reported-speech": [
        {
            "id": "rep-1", "type": "multiple_choice",
            "question": "Direct: 'I am tired.' → She said ___",
            "options": [
                "she is tired.",
                "she was tired.",
                "I am tired.",
                "she were tired.",
            ],
            "correct_answer": "she was tired.",
            "explanation": "In reported speech, present simple shifts to past simple.",
            "difficulty": "easy",
        },
        {
            "id": "rep-2", "type": "multiple_choice",
            "question": "Direct: 'I will help you.' → He said ___",
            "options": [
                "he will help me.",
                "he would help me.",
                "he would help you.",
                "he will help you.",
            ],
            "correct_answer": "he would help me.",
            "explanation": "'Will' changes to 'would' in reported speech. Pronouns also change.",
            "difficulty": "medium",
        },
        {
            "id": "rep-3", "type": "multiple_choice",
            "question": "Direct: 'Are you coming?' → She asked ___",
            "options": [
                "if I am coming.",
                "if I was coming.",
                "if was I coming.",
                "was I coming.",
            ],
            "correct_answer": "if I was coming.",
            "explanation": "Yes/no questions use 'if/whether'. No inversion in reported questions.",
            "difficulty": "medium",
        },
        {
            "id": "rep-4", "type": "multiple_choice",
            "question": "Direct: 'Close the door!' → She told him ___",
            "options": [
                "close the door.",
                "to close the door.",
                "that close the door.",
                "closing the door.",
            ],
            "correct_answer": "to close the door.",
            "explanation": "Commands are reported with tell/ask + object + to-infinitive.",
            "difficulty": "medium",
        },
        {
            "id": "rep-5", "type": "multiple_choice",
            "question": "Direct: 'Where do you live?' → He asked ___",
            "options": [
                "where do I live.",
                "where I lived.",
                "where did I live.",
                "where I live.",
            ],
            "correct_answer": "where I lived.",
            "explanation": "Wh-questions in reported speech: question word + subject + verb (no inversion, tense shifts back).",
            "difficulty": "hard",
        },
    ],

    "comparatives": [
        {
            "id": "comp-1", "type": "multiple_choice",
            "question": "She is ___ than her brother.",
            "options": ["more tall", "taller", "tallest", "the tallest"],
            "correct_answer": "taller",
            "explanation": "Short adjectives (1-2 syllables) add -er to form comparatives.",
            "difficulty": "easy",
        },
        {
            "id": "comp-2", "type": "multiple_choice",
            "question": "This is ___ film I have ever seen.",
            "options": ["more boring", "the most boring", "most boring", "the boringest"],
            "correct_answer": "the most boring",
            "explanation": "Long adjectives use 'the most' for superlatives.",
            "difficulty": "easy",
        },
        {
            "id": "comp-3", "type": "multiple_choice",
            "question": "His English is ___ than mine.",
            "options": ["more good", "gooder", "better", "more better"],
            "correct_answer": "better",
            "explanation": "'Good' is irregular. Comparative: better. Superlative: the best.",
            "difficulty": "easy",
        },
        {
            "id": "comp-4", "type": "multiple_choice",
            "question": "She is ___ her sister. (same height)",
            "options": [
                "as tall as",
                "taller than",
                "the tallest as",
                "more tall than",
            ],
            "correct_answer": "as tall as",
            "explanation": "Use 'as + adjective + as' to express equality.",
            "difficulty": "medium",
        },
        {
            "id": "comp-5", "type": "multiple_choice",
            "question": "This exercise is ___ I expected.",
            "options": [
                "more difficult than",
                "as difficult as",
                "not difficult than",
                "the most difficult",
            ],
            "correct_answer": "more difficult than",
            "explanation": "'More difficult than' is the comparative for the long adjective 'difficult'.",
            "difficulty": "medium",
        },
    ],

    "phrasal-verbs": [
        {
            "id": "pv-1", "type": "multiple_choice",
            "question": "She ___ smoking last year. (quit)",
            "options": ["gave up", "gave in", "gave out", "gave away"],
            "correct_answer": "gave up",
            "explanation": "'Give up' means to stop doing something or quit a habit.",
            "difficulty": "easy",
        },
        {
            "id": "pv-2", "type": "multiple_choice",
            "question": "Can you ___ the children while I'm out? (take care of)",
            "options": ["look for", "look after", "look up", "look into"],
            "correct_answer": "look after",
            "explanation": "'Look after' means to take care of someone or something.",
            "difficulty": "easy",
        },
        {
            "id": "pv-3", "type": "multiple_choice",
            "question": "I ___ an old friend at the supermarket yesterday. (met by chance)",
            "options": ["ran after", "ran into", "ran out", "ran away"],
            "correct_answer": "ran into",
            "explanation": "'Run into' means to meet someone unexpectedly.",
            "difficulty": "medium",
        },
        {
            "id": "pv-4", "type": "multiple_choice",
            "question": "Please ___ the lights before you leave. (switch off)",
            "options": ["turn on", "turn up", "turn off", "turn down"],
            "correct_answer": "turn off",
            "explanation": "'Turn off' means to stop a device or light from working.",
            "difficulty": "easy",
        },
        {
            "id": "pv-5", "type": "multiple_choice",
            "question": "Which sentence uses the separable phrasal verb correctly?",
            "options": [
                "Turn off them.",
                "Turn them off.",
                "Turn off it.",
                "They turn it on off.",
            ],
            "correct_answer": "Turn them off.",
            "explanation": "When the object is a pronoun (them/it/him), it MUST go between the verb and particle.",
            "difficulty": "hard",
        },
    ],
}


def get_static_grammar_questions(topic_id: str) -> list:
    # Verilen konu için statik soruları döner
    # Konu bulunamazsa boş liste döner
    return STATIC_GRAMMAR_QUESTIONS.get(topic_id, [])